### ISSUE TITLE
Provide a basic css/js example

### ISSUE THREAD

**Issue by ajibarra** [CakeDC/ratings#4]
Reported by euromark | January 25th, 2011 @ 07:57 AM

The plugin should already come with the star rating widget (jquery)
the files should be in

/ratings/webroot/css /ratings/webroot/js

A simply css stylesheet with some images, a jquery.ui.stars file and maybe an startup config file.
If desired they can be used out of the box.
Users still have the ability to include own files, though.

But I think it makes sense to include the js/css for rating in the plugin itself (as it is the only place where those files will ever be needed). So they can easily be maintained "centralized" - instead of having to update every single app that uses the plugin.

**Comment by hangal2001** [comment]
I am using Rating plugin and does not show Stars. Do i need to have following js files in webroot/js folder:
 * jquery.ui.core.js;
 * jquery.ui.widget.js;
